# File: docker-compose.yml

name: pc-remote

services:
    db:
        build: ./db
        container_name: pc-remote-db
        restart: on-failure
        user: '1010:1010'
        environment:
            - POSTGRES_PASSWORD
            - POSTGRES_INITDB_WALDR=/var/lib/postgresql/data/wal
        secrets:
            - vault_mgr_password
        networks:
            pc-remote-net:
                ipv4_address: 172.18.0.3
        volumes:
            - db-certs:/var/lib/postgresql/certs:rw
            - /home/viihna/Projects/pc-remote/secrets/certs/services/db:/vault-certs:ro
            - /home/viihna/Projects/pc-remote/secrets/certs/ca/root/:/var/lib/postgresql/ca:ro
            - /home/viihna/Projects/pc-remote/secrets/certs/ca/root/rootCA.crt:/usr/local/share/ca-certificates/rootCA.crt:ro
            - /home/viihna/Projects/pc-remote/db/data/:/var/lib/postgresql/data
            - /home/viihna/Projects/pc-remote/db/init:/docker-entrypoint.initdb.d
            - /home/viihna/Projects/pc-remote/db/conf.d/postgresql.conf:/etc/postgresql/postgresql.conf
            - /home/viihna/Projects/pc-remote/db/conf.d/pg_hba.conf:/etc/postgresql/pg_hba.conf
            - /home/viihna/Projects/pc-remote/db/conf.d/pg_ident.conf:/etc/postgresql/pg_ident.conf
            - /home/viihna/Projects/pc-remote/db/backups:/var/lib/postgresql/backups
            - type: bind
              source: /etc/ssl/projects/pc-remote/dhparam.pem
              target: /var/lib/postgresql/dhparam.pem
              read_only: true
        ports:
            - '4590:4590'
        healthcheck:
            test:
                [
                    'CMD',
                    'pg_isready',
                    '-U',
                    'postgres',
                    '-d',
                    'postgres',
                    '-h',
                    'localhost',
                    '-p',
                    '4590'
                ]
            timeout: 15s
            retries: 5
            interval: 5s
        command: ['postgres', '-c', 'config_file=/etc/postgresql/postgresql.conf']

    nginx:
        build: ./nginx
        container_name: pc-remote-nginx
        networks:
            pc-remote-net:
                ipv4_address: 172.18.0.4
        ports:
            - '192.168.50.10:444:443'
        restart: unless-stopped
        volumes:
            - /home/viihna/Projects/pc-remote/secrets/certs/services/nginx/:/etc/nginx/certs/:ro
            - /home/viihna/Projects/pc-remote/secrets/certs/ca/root/:/etc/nginx/ca/:ro
            - /home/viihna/Projects/pc-remote/logs/nginx:/var/log/nginx
            - type: bind
              source: /etc/ssl/projects/pc-remote/dhparam.pem
              target: /etc/dhparam.pem
              read_only: true
        extra_hosts:
            - 'host.docker.internal:host-gateway'

    vault-proxy:
        build: ./vault-proxy
        container_name: pc-remote-vault-proxy
    networks:
        pc-remote-net:
            ipv4_address: 172.18.0.4
    ports:
        - '192.168.50.10:445:443'
    restart: unless-stopped
    volumes:
        - /home/viihna/Projects/pc-remote/secrets/certs/services/vault-proxy/:/etc/nginx/certs/:ro
        - /home/viihna/Projects/pc-remote/secrets/certs/ca/root/:/etc/nginx/ca/:ro
        - /home/viihna/Projects/pc-remote/logs/nginx:/var/log/nginx
        - type: bind
          source: /etc/ssl/projects/pc-remote/dhparam.pem
          target: /etc/dhparam.pem
          read_only: true
    extra_hosts:
        - 'host.docker.internal:host-gateway'

    vault:
        build: ./vault
        user: '0:0'
        networks:
            pc-remote-net:
                ipv4_address: 172.18.0.2
        restart: on-failure
        cap_add:
            - IPC_LOCK
        environment:
            - VAULT_ADDR=https://192.168.50.10:4425
            - VAULT_API_ADDR=https://192.168.50.10:4425
            - VAULT_CACERT=/vault/ca/root/rootCA.crt
        ports:
            - '192.168.50.10:4425:4425'
            - '192.168.50.10:4426:4426'
        volumes:
            - /home/viihna/Projects/pc-remote/secrets/certs/services:/vault/certs:rw
            - /home/viihna/Projects/pc-remote/secrets/certs/ca/:/vault/ca:rw
            - /home/viihna/Projects/pc-remote/vault/data:/vault/data
            - /home/viihna/Projects/pc-remote/vault/config:/vault/config
            - /home/viihna/Projects/pc-remote/vault/file:/vault/file
            - /home/viihna/Projects/pc-remote/vault/policies:/vault/policies:ro
            - /home/viihna/Projects/pc-remote/vault/init/entrypoint.sh:/vault/init/entrypoint.sh
            - /home/viihna/Projects/pc-remote/vault/init/configure.sh:/vault/init/configure.sh
            - /home/viihna/Projects/pc-remote/vault/approle:/vault/approle
            - type: bind
              source: /home/viihna/Projects/pc-remote/secrets/certs/dhparam.pem
              target: /vault/dhparam.pem
              read_only: true
        healthcheck:
            test:
                [
                    'CMD',
                    'curl',
                    '-s',
                    '--cacert',
                    '/vault/ca/root/rootCA.crt',
                    'https://192.168.50.10:4425/v1/sys/health'
                ]
            interval: 5s
            timeout: 3s
            retries: 20
        extra_hosts:
            - 'pc-remote-db:192.168.50.10'

networks:
    pc-remote-net:
        driver: bridge
        ipam:
            config:
                - subnet: '172.18.0.0/16'

volumes:
    db-certs:
        name: pc-remote-db-certs

secrets:
    vault_mgr_password:
        file: ./db/secrets/vault_mgr_password
